### ISSUE TITLE
Inquiry Regarding Processing Details of Fig1D Hi-C Data

### ISSUE THREAD

**Issue by remember-past** [skelviper/HiRES#1]
Hi Zhiyuan，I hope this message finds you well. I am writing to inquire about the processing methodology used to obtain the results presented in Fig1D of the paper "Linking genome structures to functions by simultaneous single-cell Hi-C and RNA-seq."
In my analysis, I employed a 1Mb resolution for the Hi-C data and calculated the scAB value based on contacts and 1Mb CpG frequency. Subsequently, I performed rank normalization, yet the obtained results did not effectively segregate cell types as depicted in the paper (Figure 1). 
![image](https://github.com/skelviper/HiRES/assets/15341760/f5faa1b8-d042-434f-8697-ce0b7675dbec)

Figure 1

I am eager to delve into the details of how the data was processed in this context. Could you kindly provide insights or specifics regarding the data processing steps carried out to achieve the outcomes presented in Fig1D?
Thank you very much for your time and consideration. I am looking forward to your valuable guidance.

**Comment by skelviper** [comment]
Hi, sorry I'm so late in replying. I guess Prof. Xing already answered the question on WeChat for you, which is that Fig1D is implemented with schicluster(Zhou et al. PNAS 2019). So, I'll close this issue for now, if you still have any questions, you're welcome to reopen it.
