### ISSUE TITLE
refs in config.yaml

### ISSUE THREAD

**Issue by zcq23** [skelviper/HiRES#2]
Hello, I want to ask where should I download  refs (①star_index: /share/home/zliu/share/Data/public/ref_genome/mouse_ref/M23/RNA_snp_split/CAST_B6_star_index; ②snp: /share/home/zliu/share/Data/public/ref_genome/GRCm38/snp/Tan.CAST_B6.snp.GRCm38.withchr.txt; ③par: /share/home/zliu/share/Data/public/ref_genome/GRCm38/raw_data/par.bed; ④RNAsnp: /share/home/zliu/share/Data/public/ref_genome/mouse_ref/M23/RNA_snp_split/all_SNPs_CAST_EiJ_GRCm38.txt.gz) in config.yaml, thank you very much.

**Comment by skelviper** [comment]
Hi Changqing!

To download the necessary reference files for your `config.yaml`, you'll need to prepare some of these indexes and files yourself, as the specific reference genomes may vary for different users.

1. **star_index**: You can create the STAR index by following the guidance in the SNPsplit documentation. Be sure to adjust the parameters to fit your specific requirements. You can find the SNPsplit documentation here: [SNPsplit documentation](https://www.bioinformatics.babraham.ac.uk/projects/SNPsplit/).

2. **snp/RNAsnp**: For the SNP file, you'll need to download the VCF from the Mouse Genomes Project first, which you can find here: [Mouse Genomes Project - SNPs & Indels](https://www.mousegenomes.org/snps-indels/). After downloading, you can convert the format to obtain the specific strain you're interested in. A script like the one found here [dip-c script for SNPs](https://github.com/tanlongzhi/dip-c/blob/master/scripts/snp_sanger_cast_129s1.py) might be useful for this step. For RNAsnp file you can look at the SNPsplit documentation.

3. **par**: The PAR file can be obtained as described in the discussion on Biostars. Here's the link to that conversation that includes instructions on how to retrieve PAR coordinates: [Biostars - PAR coordinates](https://www.biostars.org/p/228498/).

Apologies for not being very active on GitHub issues. If you need a quicker response, feel free to reach out to me via email at zhiyuan@stu.pku.edu.cn.

Best regards,
Zhiyuan

**Comment by zcq23** [comment]
您好！

谢谢您的回复！您的回复对我来说很有帮助，真的非常谢谢您！

同时非常感谢您提供了一个可供咨询的邮箱地址，倘若以后再次遇到什么问题，还请您多多包涵，给您添麻烦了🌹🌹🌹

祝好！

长青




-----原始邮件-----
发件人:"Zhiyuan Liu" ***@***.***>
发送时间:2024-04-05 23:01:42 (星期五)
收件人: skelviper/HiRES ***@***.***>
抄送: "Zheng Changqing" ***@***.***>, Author ***@***.***>
主题: Re: [skelviper/HiRES] refs in config.yaml (Issue #2)






Hi Changqing!

To download the necessary reference files for your config.yaml, you'll need to prepare some of these indexes and files yourself, as the specific reference genomes may vary for different users.

star_index: You can create the STAR index by following the guidance in the SNPsplit documentation. Be sure to adjust the parameters to fit your specific requirements. You can find the SNPsplit documentation here: SNPsplit documentation.

snp/RNAsnp: For the SNP file, you'll need to download the VCF from the Mouse Genomes Project first, which you can find here: Mouse Genomes Project - SNPs & Indels. After downloading, you can convert the format to obtain the specific strain you're interested in. A script like the one found here dip-c script for SNPs might be useful for this step. For RNAsnp file you can look at the SNPsplit documentation.

par: The PAR file can be obtained as described in the discussion on Biostars. Here's the link to that conversation that includes instructions on how to retrieve PAR coordinates: Biostars - PAR coordinates.

Apologies for not being very active on GitHub issues. If you need a quicker response, feel free to reach out to me via email at ***@***.***

Best regards,
Zhiyuan

**Comment by Bocheng-Li** [comment]
Hi Zhiyuan!

Could you share those files you used? Thanks!

Best,
Bocheng.
