### ISSUE TITLE
Problems in DI analysis

### ISSUE THREAD

**Issue by tongy66** [skelviper/HiRES#4]
Hello, Mr. Liu;
I am very interested in the HiRES method you published in Science in 2023, which is a very important technology in the field of genome three-dimensional structure. I am also interested in the SimpleDiff analysis you mentioned for DI analysis in your paper, which is based on calculating 3D distances based on the reconstructed three-dimensional chromatin structure. However, in the GitHub repository for HiRES, I noticed that the SimpleDiff script is based on calculating distances using cooler files. How can I perform DI analysis based on the 3dg file generated by chromatin structure modeling? I look forward to and thank you for your answer.

**Comment by skelviper** [comment]
Hi tongy66:
Sorry for the late replying, in the paper we use some customized R scripts based on functions here: https://github.com/skelviper/CHARMtools/blob/main/Rlibs/d3D.R.
